"""SiangTTS **live demo** — interactive Gradio UI.

Type Thai text (optionally upload a 3-10 s reference voice) and hear the base
VoxCPM2 vs the SiangTTS LoRA side by side. Also shows the curated comparison set
generated by `src/demo.py prep` (if present) as a browse-only tab.

Companion surfaces: static page → `src/demo.py`; HTTP API → `src/serve.py`.

Run:
    uv run python -m src.live                 # http://localhost:7860
    uv run python -m src.live --share         # public gradio link
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEMO_DIR = Path("demo/samples")
MANIFEST = DEMO_DIR / "manifest.json"
DEFAULT_BASE = "openbmb/VoxCPM2"
DEFAULT_ADAPTER = "checkpoints/siangtts-lora-v0/latest"


def build_app(base_model: str = DEFAULT_BASE, adapter: str = DEFAULT_ADAPTER):
    import gradio as gr

    entries = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else []
    compare = [e for e in entries if e.get("kind") == "compare"]

    # Lazy model load — only when the user actually generates something.
    live: dict = {}

    def _ensure_live():
        if "lora" not in live:
            from .inference import Synthesizer

            live["lora"] = Synthesizer(base_model=base_model, adapter_path=adapter)
            live["base"] = Synthesizer(base_model=base_model, adapter_path=None)
        return live

    def generate(text: str, ref):
        if not text.strip():
            raise gr.Error("Enter some Thai text.")
        s = _ensure_live()
        ref_path = ref if ref else None
        sr = s["lora"].sample_rate
        return ((sr, s["base"].synth(text, ref_audio=ref_path)),
                (sr, s["lora"].synth(text, ref_audio=ref_path)))

    with gr.Blocks(title="SiangTTS — Thai TTS + Voice Cloning") as demo:
        gr.Markdown(
            "# SiangTTS — Thai Voice-Cloning TTS\n"
            "LoRA fine-tune of VoxCPM2 on Thai. Type text (+ optional reference "
            "voice) and compare the **base** model with **SiangTTS**."
        )
        with gr.Tab("Try it"):
            txt = gr.Textbox(label="Thai text", value="สวัสดีครับ ยินดีที่ได้รู้จัก")
            ref_in = gr.Audio(label="Reference voice (optional, 3–10s)", type="filepath")
            btn = gr.Button("Generate", variant="primary")
            with gr.Row():
                out_base = gr.Audio(label="Base VoxCPM2")
                out_lora = gr.Audio(label="SiangTTS (LoRA)")
            btn.click(generate, [txt, ref_in], [out_base, out_lora])

        with gr.Tab("Curated comparison"):
            if not compare:
                gr.Markdown("_Run `uv run python -m src.demo prep` first._")
            for e in compare:
                tags = f"{e['gender_est']} · {e['length']} · {e['duration']}s" + (
                    " · numeric" if e.get("has_numeric") else "")
                gr.Markdown(f"**{e['id']}** ({tags}) — {e['text']}")
                with gr.Row():
                    gr.Audio(str(DEMO_DIR / e["ref_rel"]), label="Reference")
                    gr.Audio(str(DEMO_DIR / e["ground_truth_rel"]), label="Ground truth")
                    gr.Audio(str(DEMO_DIR / e["base_rel"]), label="Base VoxCPM2")
                    gr.Audio(str(DEMO_DIR / e["lora_rel"]), label="SiangTTS (LoRA)")
    return demo


def main() -> None:
    p = argparse.ArgumentParser(description="SiangTTS live Gradio demo")
    p.add_argument("--base-model", default=DEFAULT_BASE)
    p.add_argument("--adapter", default=DEFAULT_ADAPTER)
    p.add_argument("--share", action="store_true", help="Create a public gradio link")
    p.add_argument("--port", type=int, default=7860)
    args = p.parse_args()
    build_app(base_model=args.base_model, adapter=args.adapter).launch(
        server_name="0.0.0.0", server_port=args.port, share=args.share)


if __name__ == "__main__":
    main()
